# Generated by Django 5.2.8 on 2026-06-21 14:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(blank=True, max_length=40, verbose_name='Aqoonsiga Qaranka')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefoonka')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='Magaalada')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Cinwaanka')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotaryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(blank=True, max_length=40, verbose_name='Lambarka Ruqsadda')),
                ('region', models.CharField(blank=True, max_length=80, verbose_name='Gobolka')),
                ('seal_image', models.ImageField(blank=True, null=True, upload_to='seals/', verbose_name='Sawirka Shaambooyinka')),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notary_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Cinwaanka Qaabka')),
                ('category', models.CharField(max_length=80, verbose_name='Nooca')),
                ('party_type', models.CharField(choices=[('ONE', 'Hal dhinac'), ('TWO', 'Laba dhinac')], default='ONE', max_length=4)),
                ('requires_witnesses', models.BooleanField(default=False, verbose_name='U baahan yahay marqaatiyaal')),
                ('body', models.TextField(help_text='Isticmaal {{client_name}}, {{client2_name}}, {{date}}, {{city}}, {{notary_name}}, {{notary_license}}, {{ref}} si loo buuxiyo si toos ah.', verbose_name='Qoraalka')),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='portal.notaryprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(editable=False, max_length=20, unique=True)),
                ('city', models.CharField(default='Muqdisho', max_length=80)),
                ('status', models.CharField(choices=[('PENDING', 'Sugaya'), ('SIGNED', 'La saxiixay'), ('COMPLETED', 'Dhammaystiran')], default='PENDING', max_length=10)),
                ('rendered_body', models.TextField(editable=False)),
                ('content_hash', models.CharField(editable=False, max_length=64)),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='portal.clientprofile')),
                ('client2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents_as_party2', to='portal.clientprofile')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='portal.documenttemplate')),
                ('notary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='portal.notaryprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witnesses', to='portal.document')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
