# Generated by Django 5.2.8 on 2026-06-21 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_clientprofile_signature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='pdf_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, verbose_name='SHA-256 PDF'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='body',
            field=models.TextField(help_text='Isticmaal {{client_name}}, {{client2_name}}, {{date}}, {{city}}, {{notary_name}}, {{notary_license}}, {{ref}} si loo buuxiyo si toos ah. Isticmaal {{client_signature}} (ama {{client1_signature}} / {{client2_signature}}) si loo geliyo saxiixa macmiilka.', verbose_name='Qoraalka'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('DOCUMENT_COMPLETED', 'Dokumeenti la dhammeystiray')], max_length=40)),
                ('details', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='portal.document')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
