# Generated by Django 5.2.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_document_pdf_hash_alter_documenttemplate_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaryprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefoonka'),
        ),
    ]
