# Generated by Django 5.2.8 on 2026-06-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_notaryprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaryprofile',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='notary_signatures/', verbose_name='Saxiixa'),
        ),
    ]
