# Generated by Django 5.2.8 on 2026-06-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_notaryprofile_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SIGNED', 'Signed'), ('COMPLETED', 'Completed')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='body',
            field=models.TextField(help_text="Use {{client_name}}, {{client2_name}}, {{date}}, {{city}}, {{notary_name}}, {{notary_license}}, {{ref}} to fill these in automatically. Use {{client_signature}} (or {{client1_signature}} / {{client2_signature}}) to insert the client's signature.", verbose_name='Qoraalka'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='party_type',
            field=models.CharField(choices=[('ONE', 'One Party'), ('TWO', 'Two Parties')], default='ONE', max_length=4),
        ),
    ]
